services:
  rsserver:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: 1212
        GUID: 1212
        RUN_AS: ss14
    environment:
      VERSION: 602ae8dbd7e3b6278f833042010de1a90a4ec31c
    ports:
      - 1212:1212/udp
      - 1212:1212/tcp
    volumes:
      - ./data:/home/ss14/data
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: "on-failure"
        delay: 15s
        max_attempts: 3
        window: 120s
    tty: true
    stdin_open: true
